### ISSUE TITLE
Synchronous XMLHttpRequest on the main thread

### ISSUE THREAD

**Issue by ro0gr** [ciena-blueplanet/ember-cli-visual-acceptance#102]
Currently ember-cli-visual-acceptance makes lots of sync ajax requests. I believe it may be a root cause of lagging perfomance on my local machine while running tests with several screenshots. 

Also Chrome dev tools warns that this behaviour is deprecated and is going to be removed:
![sync-ajax](https://cloud.githubusercontent.com/assets/875361/19417294/2aa8f18a-93b2-11e6-8197-bccc556eba7e.PNG)

What do you think about replacing it with async requests?

**Comment by EWhite613** [comment]
Sorry somehow missed this, school and what not. 
Ya for sure async request would be awesome. If I get some free time during I can do it. If you want to tackle it feel free.

**Comment by EWhite613** [comment]
I think my reasoning for sync was that I didn't want to miss the capture. But we could just require that the `done` callback is used or usuage is returning the capture promise.

**Comment by ro0gr** [comment]
As I can see(on my phone) _capture returns a promise already. Not sure how we can miss a capture as long as qunit and mocha both support promises as a test return value

**Comment by EWhite613** [comment]
Ya, agreed. Async should be fine and provide a nice performance boost
