### ISSUE TITLE
Move away from html2canvas?

### ISSUE THREAD

**Issue by sglanzer** [ciena-blueplanet/ember-cli-visual-acceptance#39]
Although the latest solution to the svg rendering issue has some promise, I'm concerned about the accuracy of the produced svgs (aspect ratios appear off?) and the potential for unsupported CSS properties to impact this and other elements.  http://html2canvas.hertzen.com/faq.html

Considering that html2Canvas is in alpha and we want to move `ember-cli-visual-acceptance` into use with production software, I would propose that we move back to image captures using the phantom or casper.

**Comment by EWhite613** [comment]
https://github.com/ciena-blueplanet/ember-cli-visual-acceptance/pull/42
