### ISSUE TITLE
Remove reliance on external image services

### ISSUE THREAD

**Issue by sglanzer** [ciena-blueplanet/ember-cli-visual-acceptance#40]
The project currently relies on posts to imgur to host the images in the PR comments posted to github.  This restricts the usefulness of this project for private repositories and introduces a dependency that I believe is unnecessary.

As a replacement I would propose:

- Write the images to a companion github repo for the original project (e.g. `ember-frost-core` would have a companion `ember-frost-core-visual-acceptance` repo)
- Images are written to a `visual-acceptance` branch
- A report is published to the gh-pages branch of the companion repo that tracks the changes to the visuals, reading from the `visual-acceptance` branch (this allows usage of full webpage capabilities in creating a report and removes the current PR markdown comments restriction)
- A link to the report and a summary of the changes (added, changed) is posted to the target PR
- Accepting the PR moves additions and changes into the baseline for the project

This gives us an image storage location that could potentially be private and a report that isn't restricted to PR markdown.

Open questions/thoughts:

- Authorization to create/write the companion repo: can we default to using the `ember-cli-visual-acceptance` user?
- Publishing and updating the gh-pages report site: how would the original site be published, how would the report site be upgraded if a newer version is available?
- Can the PR report be grouped with the rest of the report checks in the PR?
- For private repos, the companion repo should also be private - so the write privileges for the companion repo would need to be configurable - can the PR post still come from `ember-cli-visual-acceptance` in this case?
- How do we provide the write permissions for `ember-cli-visual-acceptance` to travis?

**Comment by sglanzer** [comment]
I don't know enough about the specifics of github tokens with travis to answer most of the open questions yet.

**Comment by EWhite613** [comment]
>Write the images to a companion github repo for the original project (e.g. ember-frost-core would have a companion ember-frost-core-visual-acceptance repo)
- Yes but obviously the repo would be under `ember-cli-visual-acceptance` and any one could use the token to do modify its repo's

The rest of the proposals would require us hosting a separate server to handle these requests. And users giving write permissions to `ember-cli-visual-acceptance`.

**Comment by sglanzer** [comment]
> The rest of the proposals would require us hosting a separate server to handle these requests. 
Why?

> Yes but obviously the repo would be under ember-cli-visual-acceptance and any one could use the token to do modify its repo's
Can you clarify this?  Are you saying the companion repos would be owned by `ember-cli-visual-acceptance`?  The intention would be to support writing to private repos with an appropriately configured token, even if that means it's not a token from the `ember-cli-visual-acceptance` user.

**Comment by EWhite613** [comment]
>Why?

- All the images would have to be written during a PR build to create our comment. Seeing as secure env variables can't be used, we would would have to have an additional server we called to utilize secure Oauth tokens that had permissions to read/write to a user's repo (they would grant a user access)

> Clarify

- Yes the repos would be owned by  `ember-cli-visual-acceptance`. I doubt anyone would wish to supply a token (Must be an unsecure env varable on travis) that grants access to read/write on both their public and private repos

**Comment by sglanzer** [comment]
I doubt even more that people want to grant access to private repos to `ember-cli-visual-acceptance`, so it looks like we need to figure out another solution to writing the images.

**Comment by sglanzer** [comment]
Ugh, why can't github just expose an API for uploading files to PR comments?...

**Comment by sglanzer** [comment]
Ok, so let's say the target for this is open source - at least for the first pass, so we go back to the idea that the companion repo is owned by `ember-cli-visual-acceptance`, this still would mean that we need to expose a write token for `ember-cli-visual-acceptance` in the unsecured travis env variables.

Other alternatives are:

* External hosting of the images (imgur - current solution - no path forward for private repos)
* Adding images as PR files (ideal for github - local generation runs into the issue of image reproducibility - can be solved a la webdriver-io server, but this is not a general market open source solution)
* Starting a service for hosting the reports (costly - not something we want responsibility for)

**Comment by sglanzer** [comment]
* An image hosting service with an option for private accounts (dropbox?)

**Comment by sglanzer** [comment]
If you have a private github repo using private travis back to a private companion repo, would you care if a r/w token for a user that only had access to the companion repo was posted in private travis unsecured env vars?

**Comment by sglanzer** [comment]
I'm becoming more comfortable with the idea that `ember-cli-visual-acceptance` (or a similarly provided account) is a sacrificial lamb that only has access to reporting (companion) repos and is therefore acceptable to expose the credentials on.

We could still ensure that the baseline images were written back to the source repo, so that someone malicious wiping out the report repos wouldn't have an impact on anything other than active reports (just re-run the travis build?)

**Comment by sglanzer** [comment]
So the purpose of the reporting repo would be to host a site for the active PR(s) and the current baseline, but the source copy of the baseline would always be kept in the source repo.

- delete PR image assets from the report repo after merge, only keep the baseline (a new baseline and comparison images would be produced for all outstanding/future PRs by the Travis process)

**Comment by sglanzer** [comment]
I need thoughts about pro/cons over the current strategy.  So far I have:

Pros:
- Better reports
- One less service in the process
- Potential to work for private repos/travis

Cons:
- Expose a write token for `ember-cli-visual-acceptance`

**Comment by sglanzer** [comment]
Closing - not enough value at this stage
