### ISSUE TITLE
bundeled jQuery overrides app jQuery 

### ISSUE THREAD

**Issue by ro0gr** [ciena-blueplanet/ember-cli-visual-acceptance#78]
I use [jquery-mockjax](https://github.com/jakerella/jquery-mockjax) in my acceptance tests. 
It's designed to intercept jquery ajax requests from application for API emulation. When I run my tests with `ember-cli-visual-acceptance` included all my acceptance tests are failing. The reason is `ember-cli-visual-acceptance`'s jquery instance overrides jquery from my app. 

So the question is can it be safely removed from `ember-cli-visual-acceptance` package?

**Comment by sglanzer** [comment]
Closed via #79
