### ISSUE TITLE
Windows is not supported

### ISSUE THREAD

**Issue by ro0gr** [ciena-blueplanet/ember-cli-visual-acceptance#92]
```
$ node_modules\.bin\ember nb
DEPRECATION: ember-try is now included with ember-cli. Including it in your package.json is unnecessary.
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn ember ENOENT
    at exports._errnoException (util.js:855:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:455:9)
    at process._tickCallback (node.js:369:17)

```
The reason is `spawn` is not able to find `ember-cli` executable installed into project. Also it isn't able to find `ember-cli` executable installed globally.

Looks like [PATHEXT](https://github.com/nodejs/node-v0.x-archive/issues/2318) issue in node for Windows.

Currently I can see 2 possible options:
- use [cross-spawn](https://www.npmjs.com/package/cross-spawn). I've tried it quickly. Seems like it partially fixes the issue. Partially because I still can't force `cross-spawn` to lookup executables in `.\node_modules\.bin` so I need to install to have `ember-cli` installed globally 
- [ember-cli's lookup-command](https://github.com/ro0gr/ember-cli-open/blob/master/lib/commands/open.js#L4). I think we don't need `spawn` at all except of `git` uses cases.

@EWhite613 @sglanzer your thoughts please?

**Comment by EWhite613** [comment]
I think we should just use the lookup command. And then just use exec for git since those commands will be relatively short and we can just make due with the buffered output ( wait till command is finished to receive output.)

**Comment by EWhite613** [comment]
Also it locks like ember-cli also uses exec for git https://github.com/ember-cli/ember-cli/blob/d8ba7dbaf77df0e7fe2daf1d153a1a5a60620143/lib/tasks/git-init.js

**Comment by sglanzer** [comment]
I'm on board with the lookup command plan - getting windows support would be nice - can run IE11 in a VM, but a native CI machine would be :+1:

**Comment by ro0gr** [comment]
Thank you for your feedback guys. I'm going to take a look at switching to 'lookupCommand' for ember commands this week.
